# Learning and practicing NumPy with examples and exercises

**Ejercicios**

In [ ]:
import numpy as np

# Definimos el array de numpy
arr = np.array([3, 7, 1, 9, 5])

# a) Recuperar el tercer elemento de la matriz
third_element = arr[2]
print("Third element:", third_element)

# b) Corta la matriz para obtener los elementos del índice 1 al índice 3
sliced_array = arr[1:4]
print("Sliced array (index 1 to 3):", sliced_array)

# c) Cambia el valor del cuarto elemento a 12
arr[3] = 12
print("Array after changing the fourth element:", arr)

Third element: 1
Sliced array (index 1 to 3): [7 1 9]
Array after changing the fourth element: [ 3  7  1 12  5]


In [3]:
# Definimos la matriz
matrix = np.array([
            [1, 2, 3],
            [4, 5, 6],  
            [7, 8, 9]
        ])

# a) Recuperamos el elemento en la fila 2, columna 3
elemento = matrix[1, 2]
print("Elemento en la fila 2, columna 3:", elemento)

# b) Corta la matriz para obtener la submatriz formada por las dos primeras filas y todas las columnas.
submatrix = matrix[:2, :]
print("Submatriz (primeras dos filas):", submatrix)

Elemento en la fila 2, columna 3: 6
Submatriz (primeras dos filas): [[1 2 3]
 [4 5 6]]


In [10]:
# Definimos el tensor 3D
tensor = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ],
    [
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]
    ]
])

# 1. Recuperar el elemento en la posición (1, 0, 2)
element_1 = tensor[1, 0, 2]
print("Elemento en la posición (1, 0, 2):", element_1)

# 2. Cortar el tensor para obtener el sub-tensor 3×4 que corresponde a la segunda "matriz" (corte) a lo largo de la primera dimensión
sub_tensor = tensor[1, :, :]
print("Sub-tensor 3×4 (segunda matriz):\n", sub_tensor)

# 3. Cortar el tensor para obtener el sub-tensor 2×4 que corresponde a la última fila de las dos últimas "matrices."
last_row_last_two_matrices = tensor[1:, 2, :]
print("Sub-tensor 2×4 (última fila de las dos últimas matrices):\n", last_row_last_two_matrices)

# 4. Recuperar el elemento en la posición (2, 1, 3)
element_2 = tensor[2, 1, 3]
print("Elemento en la posición (2, 1, 3):", element_2)

# 5. Cortar el tensor para obtener el sub-tensor 2×4 que corresponde a la primera fila de las dos últimas "matrices."
first_row_last_two_matrices = tensor[1:, 0, :]
print("Sub-tensor 2×4 (primera fila de las dos últimas matrices):\n", first_row_last_two_matrices)

Elemento en la posición (1, 0, 2): 15
Sub-tensor 3×4 (segunda matriz):
 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Sub-tensor 2×4 (última fila de las dos últimas matrices):
 [[21 22 23 24]
 [33 34 35 36]]
Elemento en la posición (2, 1, 3): 32
Sub-tensor 2×4 (primera fila de las dos últimas matrices):
 [[13 14 15 16]
 [25 26 27 28]]


In [13]:
def calculate_average(numbers):
    if not numbers:  # Evita división por cero si la lista está vacía
        return 0
    return sum(numbers) / len(numbers)

# Ejemplo de uso:
nums = [4, 8, 15, 16, 23, 42]
print(calculate_average(nums))  # Resultado: 18.0

18.0


In [16]:
def find_power(base, exponente):
    return base ** exponente

b, e = 2, 3
resultado = find_power(b, e)  # Resultado: 8

print(resultado)

8


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Datos
X = np.array([1, 2, 3, 4, 5])
y = np.array([3, 6, 8, 11, 13])

# Visualizar los datos
plt.figure(figsize=(10, 6))
plt.scatter(X, y, color='blue', marker='o', label='Datos originales')
plt.xlabel('X')
plt.ylabel('y')
plt.title('Datos para regresión lineal')
plt.grid(True)

# Normalizar los datos para un mejor rendimiento del descenso de gradiente
# En este caso simple no es necesario, pero es una buena práctica
X_norm = (X - np.mean(X)) / np.std(X)

# Parámetros
learning_rate = 0.01
num_iterations = 1000

# Inicializar los parámetros theta
theta = np.zeros(2)  # [theta_0, theta_1]

# Historial para visualizar la convergencia
J_history = np.zeros(num_iterations)

# Número de ejemplos
m = len(X)

# Añadir columna de unos para theta_0
X_b = np.c_[np.ones((m, 1)), X_norm]

# Función de costo
def compute_cost(X, y, theta):
    m = len(y)
    predictions = X.dot(theta)
    cost = (1/(2*m)) * np.sum(np.square(predictions - y))
    return cost

# Función de descenso de gradiente
def gradient_descent(X, y, theta, alpha, iterations):
    m = len(y)
    theta_history = np.zeros((iterations, 2))
    
    for i in range(iterations):
        # Calcular las predicciones con los valores actuales de theta
        predictions = X.dot(theta)
        
        # Calcular errores
        errors = predictions - y
        
        # Calcular gradientes
        gradients = (1/m) * X.T.dot(errors)
        
        # Actualizar theta
        theta = theta - alpha * gradients
        
        # Guardar historia de theta y costo
        theta_history[i, :] = theta
        J_history[i] = compute_cost(X, y, theta)
        
    return theta, J_history, theta_history

# Ejecutar descenso de gradiente
theta, J_history, theta_history = gradient_descent(X_b, y, theta, learning_rate, num_iterations)

# Desnormalizar theta para obtener parámetros para los datos originales
# theta_0 = theta[0] - theta[1] * mean(X) / std(X)
# theta_1 = theta[1] / std(X)
theta_0_original = theta[0] - theta[1] * np.mean(X) / np.std(X)
theta_1_original = theta[1] / np.std(X)

print("Theta encontrados después de la normalización:", theta)
print("Theta desnormalizados:")
print(f"theta_0 = {theta_0_original}")
print(f"theta_1 = {theta_1_original}")

# Evaluar el modelo
# Ecuación de la recta: y = theta_0 + theta_1 * x
print(f"Ecuación de la recta: y = {theta_0_original:.4f} + {theta_1_original:.4f} * x")

# Calcular R-cuadrado
y_pred = theta_0_original + theta_1_original * X
ss_total = np.sum((y - np.mean(y))**2)
ss_residual = np.sum((y - y_pred)**2)
r_squared = 1 - (ss_residual / ss_total)
print(f"R-cuadrado: {r_squared:.4f}")

# Visualizar la convergencia del costo
plt.figure(figsize=(10, 6))
plt.plot(range(num_iterations), J_history)
plt.xlabel('Iteraciones')
plt.ylabel('Costo J')
plt.title('Convergencia del descenso de gradiente')
plt.grid(True)

# Visualizar la línea de regresión
plt.figure(figsize=(10, 6))
plt.scatter(X, y, color='blue', marker='o', label='Datos originales')
plt.plot(X, y_pred, color='red', label='Línea de regresión')
plt.xlabel('X')
plt.ylabel('y')
plt.title('Regresión Lineal con Descenso de Gradiente')
plt.legend()
plt.grid(True)

# Calcular predicciones para algunos valores
x_test = np.array([0, 6])
y_test = theta_0_original + theta_1_original * x_test
print(f"Predicciones: Para x=0: {y_test[0]:.2f}, Para x=6: {y_test[1]:.2f}")

# Mostrar todo
plt.tight_layout()
plt.show()

Theta final: [[0.69871031]
 [2.50035722]]
